/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigyula;

/**
 *
 * @author Kiss Bence
 */
public class Fomenu extends javax.swing.JFrame {

    private static boolean admin;
    /**
     * Creates new form Fomenu
     * @param admin
     */
    public Fomenu(boolean admin) {
        Fomenu.admin = admin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Karbantartas = new javax.swing.JMenu();
        jMI_Ujfelh = new javax.swing.JMenuItem();
        jMI_Ujterm = new javax.swing.JMenuItem();
        jMI_Ujtermcsop = new javax.swing.JMenuItem();
        jM_Ugyvitel = new javax.swing.JMenu();
        jMI_Eladas = new javax.swing.JMenuItem();
        jMI_Kimutatás = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Főmenü");
        setName("Fomenu"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigyula/bigyulabolt.jpg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jM_Karbantartas.setText("Karbantartás");
        jM_Karbantartas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMI_Ujfelh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMI_Ujfelh.setText("Új felhasználó");
        jMI_Ujfelh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_UjfelhActionPerformed(evt);
            }
        });
        jM_Karbantartas.add(jMI_Ujfelh);

        jMI_Ujterm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMI_Ujterm.setText("Új termék/termék módosítása");
        jMI_Ujterm.setEnabled(false);
        jM_Karbantartas.add(jMI_Ujterm);

        jMI_Ujtermcsop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMI_Ujtermcsop.setText("Új termékcsoport");
        jMI_Ujtermcsop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_UjtermcsopActionPerformed(evt);
            }
        });
        jM_Karbantartas.add(jMI_Ujtermcsop);

        jMenuBar1.add(jM_Karbantartas);

        jM_Ugyvitel.setText("Ügyvitel");
        jM_Ugyvitel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMI_Eladas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMI_Eladas.setText("Eladás");
        jM_Ugyvitel.add(jMI_Eladas);

        jMI_Kimutatás.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMI_Kimutatás.setText("Kimutatás");
        jMI_Kimutatás.setEnabled(false);
        jM_Ugyvitel.add(jMI_Kimutatás);

        jMenuBar1.add(jM_Ugyvitel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMI_UjfelhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_UjfelhActionPerformed
        UjFelh ujfelh = new UjFelh();
        ujfelh.setVisible(true);
    }//GEN-LAST:event_jMI_UjfelhActionPerformed

    private void jMI_UjtermcsopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_UjtermcsopActionPerformed
        UjTermCsop ujtermcsop = new UjTermCsop();
        ujtermcsop.setVisible(true);
    }//GEN-LAST:event_jMI_UjtermcsopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fomenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fomenu(admin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMI_Eladas;
    private javax.swing.JMenuItem jMI_Kimutatás;
    private javax.swing.JMenuItem jMI_Ujfelh;
    private javax.swing.JMenuItem jMI_Ujterm;
    private javax.swing.JMenuItem jMI_Ujtermcsop;
    private javax.swing.JMenu jM_Karbantartas;
    private javax.swing.JMenu jM_Ugyvitel;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
