/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigyula;

import com.sun.glass.events.KeyEvent;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lakatos Ildikó
 */
public class Kimutatas extends javax.swing.JFrame {

    /**
     * Creates new form Kimutatas
     */
    public Kimutatas() {
        initComponents();
        jT_Eladasok.getTableHeader().setFont(new Font("Arial",Font.BOLD, 18));
        jT_Eladasok.setFont(new Font("Arial",Font.ITALIC, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTF_Osszeladas = new javax.swing.JTextField();
        jBtn_Atvaltas = new javax.swing.JButton();
        jBtn_Vissza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_Euro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF_Arfolyam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Eladasok = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTF_Osszeladas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTF_Osszeladas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_OsszeladasKeyTyped(evt);
            }
        });

        jBtn_Atvaltas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtn_Atvaltas.setText("Átváltás");
        jBtn_Atvaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AtvaltasActionPerformed(evt);
            }
        });

        jBtn_Vissza.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtn_Vissza.setText("Vissza");
        jBtn_Vissza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VisszaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kimutatás");

        jTF_Euro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Összeladás:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Euró");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ft");

        jTF_Arfolyam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTF_Arfolyam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_ArfolyamKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Árfolyam:");

        jT_Eladasok.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jT_Eladasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Termékcsoport", "Összeladás"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_Eladasok);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Termékcsoportok eladásai:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtn_Vissza)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTF_Euro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTF_Arfolyam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTF_Osszeladas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtn_Atvaltas)))))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Osszeladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Arfolyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jBtn_Atvaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Euro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Vissza)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_OsszeladasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_OsszeladasKeyTyped
        char c = evt.getKeyChar();
        if (jTF_Osszeladas.getText().length() == 0 && c == '0') {
            evt.consume();
        }
        if ((c < '0' || c > '9') && c != KeyEvent.VK_BACKSPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jTF_OsszeladasKeyTyped

    private void jBtn_AtvaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AtvaltasActionPerformed
        if (jTF_Osszeladas.getText().equals("") || jTF_Arfolyam.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Üres mező nem lehet!");
            return;
        }
        
        double osszeladas;
        double arfolyam;
        
        try {
            osszeladas = Double.parseDouble(jTF_Osszeladas.getText());
            arfolyam = Double.parseDouble(jTF_Arfolyam.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Hiba a bevitt adatokban: " + e.getMessage());
            return;
        }
        
        if (arfolyam <= 0) {
            JOptionPane.showMessageDialog(null, "Nulla és annál kisebb nem lehet az árfolyam!");
            return;
        }

        jTF_Euro.setText(String.format("%.2f", osszeladas / arfolyam));
    }//GEN-LAST:event_jBtn_AtvaltasActionPerformed

    private void jBtn_VisszaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VisszaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtn_VisszaActionPerformed

    private void jTF_ArfolyamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_ArfolyamKeyTyped
        char c = evt.getKeyChar();
        
        boolean startsWithPoint = jTF_Arfolyam.getText().length() == 0 && c == '.';
        boolean startsWithZero = jTF_Arfolyam.getText().length() == 0 && c == '0';
        boolean alreadyContainsPoint = jTF_Arfolyam.getText().contains(".") && c == '.';
        if (startsWithPoint || startsWithZero || alreadyContainsPoint) {
            evt.consume();
        }
        
        boolean NaN = c < '0' || c > '9'; // NaN = not a number (JS)
        boolean notBackspace = c != KeyEvent.VK_BACKSPACE;
        boolean notPoint = c != '.';
        if (NaN && notBackspace && notPoint) {
            evt.consume();
        }
    }//GEN-LAST:event_jTF_ArfolyamKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            MySQL mysql = new MySQL();
            String[] ertekek = {};
            PreparedStatement psta = mysql.getStatement("SELECT SUM(eladas) FROM kimutatas;", ertekek);
            ResultSet rs = psta.executeQuery();
            rs.next();
            jTF_Osszeladas.setText(String.valueOf(rs.getInt("SUM(eladas)")));
            
            psta = mysql.getStatement("SELECT * FROM kimutatas;", ertekek);
            rs = psta.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel)jT_Eladasok.getModel();
            while (rs.next()) {
                dtm.addRow(new Object[] {rs.getString(1), rs.getInt(2)});
            }
            
            
            psta.close();
            mysql.finalize();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hiba a felhasználó felvételekor: " + ex.getMessage());
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kimutatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kimutatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kimutatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kimutatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kimutatas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Atvaltas;
    private javax.swing.JButton jBtn_Vissza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_Arfolyam;
    private javax.swing.JTextField jTF_Euro;
    private javax.swing.JTextField jTF_Osszeladas;
    private javax.swing.JTable jT_Eladasok;
    // End of variables declaration//GEN-END:variables
}
